# Generated by Django 5.2.7 on 2025-11-06 13:41

import uuid

import django.core.serializers.json
import django.utils.timezone
from django.db import migrations, models

import django_jsonform.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExterneTaak",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Een UUID waarmee een ZAC een link kan leggen tussen de taak en zijn eigen administratie.",
                        unique=True,
                    ),
                ),
                (
                    "titel",
                    models.CharField(
                        help_text="Titel van de taak (max. 1 zin)",
                        max_length=100,
                        verbose_name="titel",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("uitgevoerd", "Uitgevoerd"),
                            ("niet_uitgevoerd", "Niet uitgevoerd"),
                            ("afgebroken", "Afgebroken"),
                            ("verwerkt", "Verwerkt"),
                        ],
                        default="open",
                        help_text="Status van de taak",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "startdatum",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Startdatum van de taak.",
                        verbose_name="start datum",
                    ),
                ),
                (
                    "handelings_perspectief",
                    models.CharField(
                        help_text="Handelings perspectief",
                        max_length=100,
                        verbose_name="handelings perspectief",
                    ),
                ),
                (
                    "einddatum_handelings_termijn",
                    models.DateTimeField(
                        blank=True,
                        help_text="Einddatum handelings termijn",
                        null=True,
                        verbose_name="einddatum handelings termijn",
                    ),
                ),
                (
                    "datum_herinnering",
                    models.DateTimeField(
                        blank=True,
                        help_text="Datum Herinnering",
                        null=True,
                        verbose_name="datum herinnering",
                    ),
                ),
                (
                    "toelichting",
                    models.TextField(
                        blank=True,
                        help_text="Uitleg van de taak",
                        verbose_name="toelichting",
                    ),
                ),
                (
                    "taak_soort",
                    models.CharField(
                        choices=[
                            ("betaaltaak", "Betaallink"),
                            ("gegevensuitvraagtaak", "Extern formulier"),
                            ("formuliertaak", "Standaard formulier"),
                        ],
                        help_text="Het soort taak",
                        max_length=20,
                        verbose_name="taak soort",
                    ),
                ),
                (
                    "data",
                    django_jsonform.models.fields.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Data van de taak met validaties op basis van het soort taak",
                        verbose_name="data",
                    ),
                ),
            ],
            options={
                "verbose_name": "Externe taak",
                "verbose_name_plural": "Externe taken",
            },
        ),
    ]
