# Generated by Django 5.2.7 on 2025-12-15 13:54

import uuid

import django.core.serializers.json
import django.utils.timezone
from django.db import migrations, models

import django_jsonform.models.fields

import openvtb.utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExterneTaak",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Een UUID waarmee een ZAC een link kan leggen tussen de taak en zijn eigen administratie.",
                        unique=True,
                    ),
                ),
                (
                    "titel",
                    models.CharField(
                        help_text="Titel van de taak (max. 1 zin)",
                        max_length=100,
                        verbose_name="titel",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("uitgevoerd", "Uitgevoerd"),
                            ("niet_uitgevoerd", "Niet uitgevoerd"),
                            ("afgebroken", "Afgebroken"),
                            ("verwerkt", "Verwerkt"),
                        ],
                        default="open",
                        help_text="Status van de taak",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "startdatum",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Startdatum van de taak.",
                        verbose_name="start datum",
                    ),
                ),
                (
                    "handelings_perspectief",
                    models.CharField(
                        help_text="Handelings perspectief",
                        max_length=100,
                        verbose_name="handelings perspectief",
                    ),
                ),
                (
                    "einddatum_handelings_termijn",
                    models.DateTimeField(
                        blank=True,
                        help_text="Einddatum handelings termijn",
                        null=True,
                        verbose_name="einddatum handelings termijn",
                    ),
                ),
                (
                    "datum_herinnering",
                    models.DateTimeField(
                        blank=True,
                        help_text="Datum Herinnering",
                        null=True,
                        verbose_name="datum herinnering",
                    ),
                ),
                (
                    "toelichting",
                    models.TextField(
                        blank=True,
                        help_text="Uitleg van de taak",
                        verbose_name="toelichting",
                    ),
                ),
                (
                    "taak_soort",
                    models.CharField(
                        choices=[
                            ("betaaltaak", "Betaallink"),
                            ("gegevensuitvraagtaak", "Extern formulier"),
                            ("formuliertaak", "Standaard formulier"),
                        ],
                        help_text="Het soort taak",
                        max_length=20,
                        verbose_name="taak soort",
                    ),
                ),
                (
                    "details",
                    django_jsonform.models.fields.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Details van de taak met validaties op basis van het soort taak",
                        verbose_name="details",
                    ),
                ),
                (
                    "is_toegewezen_aan",
                    openvtb.utils.fields.URNField(
                        blank=True,
                        help_text="De persoon of partij aan wie deze taak is toegewezen. Kan een van de volgende types zijn: PARTIJ, NATUURLIJK PERSOON of NIET NATUURLIJK PERSOON.",
                        max_length=255,
                        verbose_name="is toegewezen aan partij",
                    ),
                ),
                (
                    "wordt_behandeld_door",
                    openvtb.utils.fields.URNField(
                        blank=True,
                        help_text="De medewerker die verantwoordelijk is voor de uitvoering van deze taak. Kan een entiteit van het type MEDEWERKER zijn.",
                        max_length=255,
                        verbose_name="wordt behandeld door medewerker",
                    ),
                ),
                (
                    "hoort_bij",
                    openvtb.utils.fields.URNField(
                        blank=True,
                        help_text="De zaak waartoe deze taak behoort, waarmee de taak kan worden gekoppeld aan een specifieke zaak.",
                        max_length=255,
                        verbose_name="hoort bij zaak",
                    ),
                ),
                (
                    "heeft_betrekking_op",
                    openvtb.utils.fields.URNField(
                        blank=True,
                        help_text="Het product waarop deze taak betrekking heeft",
                        max_length=255,
                        verbose_name="heeft betrekking op product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Externe taak",
                "verbose_name_plural": "Externe taken",
            },
        ),
    ]
