# Generated by Django 5.2.15 on 2026-06-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externetaak",
            name="handelings_perspectief",
            field=models.CharField(
                blank=True,
                choices=[
                    ("betalen", "Betalen"),
                    ("incasso", "Incasso"),
                    ("informatie_geven", "Informatie geven"),
                    ("informatie_krijgen", "Informatie krijgen"),
                    ("reactie_ontvangen", "Reactie ontvangen"),
                    ("vernieuwing_nodig", "Vernieuwing nodig"),
                    ("uitnodiging_voor_afspraak", "Uitnodiging voor afspraak"),
                ],
                help_text="De door de toegewezen persoon of bedrijf uit te voeren handeling.",
                max_length=100,
                verbose_name="handelings perspectief",
            ),
        ),
    ]
