# Generated by Django 5.2.15 on 2026-07-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taken", "0002_alter_externetaak_handelings_perspectief"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externetaak",
            name="verwerker_taak_id",
            field=models.CharField(
                blank=True,
                help_text="De identifier waarmee een taak door een verwerkende component wordt gecorreleerd aan het onderliggende proces in een workflow-engine.",
                max_length=36,
                verbose_name="verwerker taak id",
            ),
        ),
    ]
