# Generated by Django 5.2.12 on 2026-04-21 10:23

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import openvtb.utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bericht",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatiecode (UUID4) voor het Bericht.",
                        unique=True,
                    ),
                ),
                (
                    "onderwerp",
                    models.CharField(
                        help_text="Onderwerp van het bericht.",
                        max_length=50,
                        verbose_name="onderwerp",
                    ),
                ),
                (
                    "bericht_tekst",
                    models.TextField(
                        help_text="Tekst van het bericht. URLs worden altijd weergegeven als klikbare URLs op alle portalen. Voor portalen van lokale overheden is de basic syntax van Markdown toegestaan, voor de Mijn Overheid berichtenbox enkel newlines (\\r\\n).",
                        max_length=4000,
                        verbose_name="bericht tekst",
                    ),
                ),
                (
                    "publicatiedatum",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Datum/tijd waarop bericht zichtbaar moet worden voor de ontvanger. Dit geldt voor zowel de Mijn Overheid berichtenbox als het portaal van de lokale overheid. De standaardwaarde is de huidige datum/tijd.",
                        null=True,
                        verbose_name="publicatiedatum",
                    ),
                ),
                (
                    "is_gepubliceerd",
                    models.BooleanField(
                        default=False,
                        help_text="Geeft aan of het object gepubliceerd is en zichtbaar voor gebruikers.",
                        verbose_name="gepubliceerd",
                    ),
                ),
                (
                    "referentie",
                    models.CharField(
                        blank=True,
                        help_text="Zenderreferentie / interne referentie.",
                        max_length=25,
                        verbose_name="referentie",
                    ),
                ),
                (
                    "ontvanger",
                    openvtb.utils.fields.URNField(
                        help_text="URN van een NATUURLIJK PERSOON of NIET-NATUURLIJK PERSOON. Bijvoorbeeld: `urn:nld:brp:bsn:111222333`, `urn:nld:hr:kvknummer:444555666` of `urn:nld:hr:kvknummer:444555666:vestigingsnummer:777888999`",
                        max_length=255,
                        verbose_name="ontvanger",
                    ),
                ),
                (
                    "geopend_op",
                    models.DateTimeField(
                        help_text="Het bericht is door de geadresseerde geopend op dit tijdstip in het portaal van de lokale overheid. Deze waarde is onafhankelijk Mijn Overheid.",
                        null=True,
                        verbose_name="geopend op",
                    ),
                ),
                (
                    "bericht_type",
                    models.CharField(
                        blank=True,
                        help_text="Een code die hoort bij het sjabloon zoals gebruikt in de Mijn Overheid berichtenbox. Indien dit een geldige waarde bevat, wordt het bericht doorgezet naar Mijn Overheid berichtenbox. In de andere gevallen is het bericht enkel op het portaal van de lokale overheid te zien.",
                        max_length=8,
                        verbose_name="bericht type",
                    ),
                ),
                (
                    "handelings_perspectief",
                    models.CharField(
                        blank=True,
                        help_text="De door de toegewezen persoon of bedrijf uit te voeren handeling. Bijvoorbeeld: `lezen`, `naleveren`, `invullen`.",
                        max_length=50,
                        verbose_name="handelings perspectief",
                    ),
                ),
                (
                    "einddatum_handelings_termijn",
                    models.DateTimeField(
                        help_text="Datum/tijd waarop handeling afgerond moet zijn.",
                        null=True,
                        verbose_name="einddatum handelings termijn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bericht",
                "verbose_name_plural": "Berichten",
            },
        ),
        migrations.CreateModel(
            name="Bijlage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatiecode (UUID4) voor het Bijlage.",
                        unique=True,
                    ),
                ),
                (
                    "informatie_object",
                    openvtb.utils.fields.URNField(
                        help_text="URN naar het ENKELVOUDIGINFORMATIEOBJECT. Bijvoorbeeld: `urn:nld:gemeenteutrecht:informatieobject:uuid:717815f6-1939-4fd2-93f0-83d25bad154e`",
                        max_length=255,
                        verbose_name="informatie object",
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(
                        blank=True,
                        help_text="Een korte omschrijving of de titel van de bijlage. Deze wordt typisch getoond in een portaal.",
                        max_length=40,
                        verbose_name="omschrijving",
                    ),
                ),
                (
                    "is_bericht_type_bijlage",
                    models.BooleanField(
                        default=False,
                        help_text="Geeft aan of het een bijlage betreft die onderdeel is van het sjabloon in de Mijn Overheid berichtenbox. Indien `true`, dan wordt deze bijlage niet doorgestuurd naar de Mijn Overheid berichtenbox. De verwachting is dat eenzelfde bericht reeds onderdeel is van het sjabloon.",
                        verbose_name="is bericht type bijlage",
                    ),
                ),
                (
                    "bericht",
                    models.ForeignKey(
                        help_text="Bijlagen gekoppeld aan het bericht.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bijlagen",
                        to="berichten.bericht",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bericht bijlage",
                "verbose_name_plural": "Berichten bijlagen",
                "unique_together": {("bericht", "informatie_object")},
            },
        ),
    ]
