# Generated by Django 5.2.17 on 2026-10-06 14:39

import uuid

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import openvtb.utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BerichtType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatiecode (UUID4) voor het BerichtType.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "handelings_perspectief",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("betalen", "Betalen"),
                            ("incasso", "Incasso"),
                            ("informatie_geven", "Informatie geven"),
                            ("informatie_krijgen", "Informatie krijgen"),
                            ("reactie_ontvangen", "Reactie ontvangen"),
                            ("vernieuwing_nodig", "Vernieuwing nodig"),
                            ("uitnodiging_voor_afspraak", "Uitnodiging voor afspraak"),
                        ],
                        help_text="De door de toegewezen persoon of bedrijf uit te voeren handeling.",
                        max_length=50,
                        verbose_name="handelings perspectief",
                    ),
                ),
                (
                    "mijn_overheid_berichtenbox",
                    models.BooleanField(
                        help_text="Geeft aan of berichten van dit type geschikt zijn voor publicatie in de MijnOverheid Berichtenbox. Als dit op ``False`` staat, zijn berichten van dit type niet bedoeld voor publicatie in de Berichtenbox.",
                        verbose_name="Mijn Overheid Berichtenbox",
                    ),
                ),
                (
                    "mijn_overheid_berichtenbox_type",
                    models.CharField(
                        blank=True,
                        help_text="Een code voor het technisch identificeren van een bericht soort & origine. Wordt gebruikt in de Mijn Overheid berichtenbox.",
                        max_length=8,
                        verbose_name="Mijn Overheid Berichtenbox Type",
                    ),
                ),
                (
                    "verantwoordelijke_organisatie",
                    openvtb.utils.fields.URNField(
                        help_text="Geeft aan welk onderdeel van de organisatie de eigenaar is van dit berichtType. Kan bijv. gebruikt worden voor routering, administratieve doeleinden en zichtbaarheid in de keten.",
                        max_length=255,
                        verbose_name="verantwoordelijke organisatie",
                    ),
                ),
            ],
            options={
                "verbose_name": "BerichtType",
                "verbose_name_plural": "BerichtTypen",
            },
        ),
        migrations.CreateModel(
            name="Bericht",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatiecode (UUID4) voor het Bericht.",
                        unique=True,
                    ),
                ),
                (
                    "onderwerp",
                    models.CharField(
                        help_text="Onderwerp van het bericht.",
                        max_length=50,
                        verbose_name="onderwerp",
                    ),
                ),
                (
                    "tekst",
                    models.TextField(
                        blank=True,
                        help_text="Tekst van het bericht. URLs worden altijd weergegeven als klikbare URLs op alle portalen. Voor portalen van lokale overheden is de basic syntax van Markdown toegestaan, voor de Mijn Overheid berichtenbox enkel newlines (\\r\\n).",
                        max_length=4000,
                        verbose_name="tekst",
                    ),
                ),
                (
                    "publicatiedatum",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Datum/tijd waarop bericht zichtbaar moet worden voor de ontvanger. Dit geldt voor zowel de Mijn Overheid berichtenbox als het portaal van de lokale overheid. De standaardwaarde is de huidige datum/tijd.",
                        null=True,
                        verbose_name="publicatiedatum",
                    ),
                ),
                (
                    "is_gepubliceerd",
                    models.BooleanField(
                        default=False,
                        help_text="Geeft aan of het object gepubliceerd is en zichtbaar voor gebruikers.",
                        verbose_name="gepubliceerd",
                    ),
                ),
                (
                    "referentie",
                    models.CharField(
                        blank=True,
                        help_text="Uw eigen optionele referentiegegevens, maximaal 25 tekens, conform de requirements van Logius in haar technische aansluithandleiding.",
                        max_length=25,
                        verbose_name="referentie",
                    ),
                ),
                (
                    "ontvanger",
                    openvtb.utils.fields.URNField(
                        help_text="URN van een NATUURLIJK PERSOON of NIET-NATUURLIJK PERSOON. Bijvoorbeeld: `urn:nld:brp:bsn:111222333`, `urn:nld:hr:kvknummer:444555666` of `urn:nld:hr:kvknummer:444555666:vestigingsnummer:777888999`",
                        max_length=255,
                        verbose_name="ontvanger",
                    ),
                ),
                (
                    "geopend_op",
                    models.DateTimeField(
                        help_text="Het bericht is door de geadresseerde geopend op dit tijdstip in het portaal van de lokale overheid. Deze waarde is onafhankelijk Mijn Overheid.",
                        null=True,
                        verbose_name="geopend op",
                    ),
                ),
                (
                    "einddatum_handelings_termijn",
                    models.DateTimeField(
                        help_text="Datum/tijd waarop handeling afgerond moet zijn.",
                        null=True,
                        verbose_name="einddatum handelings termijn",
                    ),
                ),
                (
                    "is_gerelateerd_aan",
                    models.JSONField(
                        blank=True,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Lijst met URN’s naar de ZAAK of het PRODUCT.",
                        null=True,
                        verbose_name="is gerelateerd aan",
                    ),
                ),
                (
                    "bericht_type",
                    models.ForeignKey(
                        help_text="Het berichttype waartoe dit bericht behoort.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="berichten",
                        to="berichten.berichttype",
                        verbose_name="bericht type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bericht",
                "verbose_name_plural": "Berichten",
            },
        ),
        migrations.CreateModel(
            name="Bijlage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatiecode (UUID4) voor het Bijlage.",
                        unique=True,
                    ),
                ),
                (
                    "informatie_object",
                    openvtb.utils.fields.URNField(
                        help_text="URN naar het ENKELVOUDIGINFORMATIEOBJECT. Bijvoorbeeld: `urn:nld:gemeenteutrecht:informatieobject:uuid:717815f6-1939-4fd2-93f0-83d25bad154e`",
                        max_length=255,
                        verbose_name="informatie object",
                    ),
                ),
                (
                    "omschrijving",
                    models.CharField(
                        blank=True,
                        help_text="Een door de inwoner of bedrijf goed leesbare omschrijving van de bijlage die wordt weergegeven als bestandsnaam in een berichtenbox of portaal.",
                        max_length=40,
                        verbose_name="omschrijving",
                    ),
                ),
                (
                    "bericht",
                    models.ForeignKey(
                        help_text="Bijlagen gekoppeld aan het bericht.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bijlagen",
                        to="berichten.bericht",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bericht bijlage",
                "verbose_name_plural": "Berichten bijlagen",
                "unique_together": {("bericht", "informatie_object")},
            },
        ),
        migrations.CreateModel(
            name="BijlageType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatiecode (UUID4) voor het BijlageType.",
                        unique=True,
                    ),
                ),
                (
                    "informatie_objecttype",
                    openvtb.utils.fields.URNField(
                        blank=True,
                        help_text="URN van het INFORMATIEOBJECTTYPE. Bijvoorbeeld: `urn:nld:gemeenteutrecht:informatieobjecttype:uuid:717815f6-1939-4fd2-93f0-83d25bad154e`",
                        max_length=255,
                        verbose_name="informatie objecttype",
                    ),
                ),
                (
                    "omschrijving",
                    models.TextField(
                        blank=True,
                        help_text="Omschrijving van het soort bijlage, zoals dat door eind gebruikers gezien kan worden in bijvoorbeeld een portaal. Typisch is dit dezelfde omschrijving als die van het INFORMATIEOBJECTTYPE.",
                        max_length=4000,
                        verbose_name="omschrijving",
                    ),
                ),
                (
                    "bericht_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bijlage_typen",
                        to="berichten.berichttype",
                        verbose_name="bericht type",
                    ),
                ),
            ],
            options={
                "verbose_name": "BijlageType",
                "verbose_name_plural": "BijlageTypen",
                "unique_together": {("bericht_type", "informatie_objecttype")},
            },
        ),
    ]
