# Generated by Django 5.2.15 on 2026-06-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("berichten", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bericht",
            name="referentie",
            field=models.CharField(
                blank=True,
                help_text="Uw eigen optionele referentiegegevens, maximaal 25 tekens, conform de requirements van Logius in haar technische aansluithandleiding.",
                max_length=25,
                verbose_name="referentie",
            ),
        ),
    ]
