# Generated by Django 5.2.15 on 2026-07-17 12:26

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("berichten", "0002_alter_bericht_handelings_perspectief_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bericht",
            name="is_gerelateerd_aan",
            field=models.JSONField(
                blank=True,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Lijst met URN’s naar de ZAAK of het PRODUCT.",
                null=True,
                verbose_name="is gerelateerd aan",
            ),
        ),
    ]
