# Generated by Django 5.2.17 on 2026-08-31 07:54

import uuid

import django.db.models.deletion
from django.db import migrations, models

import openvtb.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("berichten", "0003_alter_bericht_is_gerelateerd_aan"),
    ]

    operations = [
        migrations.CreateModel(
            name="BerichtType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatiecode (UUID4) voor het BerichtType.",
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "handelings_perspectief",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("betalen", "Betalen"),
                            ("incasso", "Incasso"),
                            ("informatie_geven", "Informatie geven"),
                            ("informatie_krijgen", "Informatie krijgen"),
                            ("reactie_ontvangen", "Reactie ontvangen"),
                            ("vernieuwing_nodig", "Vernieuwing nodig"),
                            ("uitnodiging_voor_afspraak", "Uitnodiging voor afspraak"),
                        ],
                        help_text="De door de toegewezen persoon of bedrijf uit te voeren handeling.",
                        max_length=50,
                        verbose_name="handelings perspectief",
                    ),
                ),
                (
                    "mijn_overheid_berichtenbox",
                    models.BooleanField(
                        help_text="Geeft aan of berichten van dit type geschikt zijn voor publicatie in de MijnOverheid Berichtenbox. Als dit op ``False`` staat, zijn berichten van dit type niet bedoeld voor publicatie in de Berichtenbox.",
                        verbose_name="Mijn Overheid Berichtenbox",
                    ),
                ),
                (
                    "mijn_overheid_berichtenbox_type",
                    models.CharField(
                        blank=True,
                        help_text="Een code voor het technisch identificeren van een bericht soort & origine. Wordt gebruikt in de Mijn Overheid berichtenbox.",
                        max_length=8,
                        verbose_name="Mijn Overheid Berichtenbox Type",
                    ),
                ),
                (
                    "verantwoordelijke_organisatie",
                    openvtb.utils.fields.URNField(
                        help_text="Geeft aan welk onderdeel van de organisatie de eigenaar is van dit berichtType. Kan bijv. gebruikt worden voor routering, administratieve doeleinden en zichtbaarheid in de keten.",
                        max_length=255,
                        verbose_name="verantwoordelijke organisatie",
                    ),
                ),
            ],
            options={
                "verbose_name": "BerichtType",
                "verbose_name_plural": "BerichtTypen",
            },
        ),
        migrations.RemoveField(
            model_name="bericht",
            name="handelings_perspectief",
        ),
        migrations.RemoveField(
            model_name="bericht",
            name="mijn_overheid_berichtenbox",
        ),
        migrations.RemoveField(
            model_name="bijlage",
            name="is_bericht_type_bijlage",
        ),
        migrations.AlterField(
            model_name="bericht",
            name="bericht_type",
            field=models.ForeignKey(
                help_text="Het berichttype waartoe dit bericht behoort.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="berichten",
                to="berichten.berichttype",
                verbose_name="bericht type",
            ),
        ),
        migrations.CreateModel(
            name="BijlageType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatiecode (UUID4) voor het BijlageType.",
                        unique=True,
                    ),
                ),
                (
                    "informatie_objecttype",
                    openvtb.utils.fields.URNField(
                        blank=True,
                        help_text="URN van het INFORMATIEOBJECTTYPE. Bijvoorbeeld: `urn:nld:gemeenteutrecht:informatieobjecttype:uuid:717815f6-1939-4fd2-93f0-83d25bad154e`",
                        max_length=255,
                        verbose_name="informatie objecttype",
                    ),
                ),
                (
                    "omschrijving",
                    models.TextField(
                        blank=True,
                        help_text="Omschrijving van het soort bijlage, zoals dat door eind gebruikers gezien kan worden in bijvoorbeeld een portaal. Typisch is dit dezelfde omschrijving als die van het INFORMATIEOBJECTTYPE.",
                        max_length=4000,
                        verbose_name="omschrijving",
                    ),
                ),
                (
                    "bericht_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bijlage_typen",
                        to="berichten.berichttype",
                        verbose_name="bericht type",
                    ),
                ),
            ],
            options={
                "verbose_name": "BijlageType",
                "verbose_name_plural": "BijlageTypen",
                "unique_together": {("bericht_type", "informatie_objecttype")},
            },
        ),
    ]
