# Generated by Django 5.2.17 on 2026-08-27 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "berichten",
            "0004_berichttype_remove_bericht_handelings_perspectief_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bijlagetype",
            name="bericht_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bijlage_typen",
                to="berichten.berichttype",
                verbose_name="bericht type",
            ),
        ),
    ]
