# Generated by Django 5.2.17 on 2026-10-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "berichten",
            "0004_berichttype_remove_bericht_handelings_perspectief_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bericht",
            name="bericht_tekst",
        ),
        migrations.AddField(
            model_name="bericht",
            name="tekst",
            field=models.TextField(
                blank=True,
                help_text="Tekst van het bericht. URLs worden altijd weergegeven als klikbare URLs op alle portalen. Voor portalen van lokale overheden is de basic syntax van Markdown toegestaan, voor de Mijn Overheid berichtenbox enkel newlines (\\r\\n).",
                max_length=4000,
                verbose_name="tekst",
            ),
        ),
    ]
