---

extensions:
  basicauth/server:
    htpasswd:
      inline: |
        otel:supersecret

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        # auth:
        #   authenticator: basicauth/server
      http:
        endpoint: 0.0.0.0:4318
        # auth:
        #   authenticator: basicauth/server

processors:
  batch:
    timeout: 1s
    send_batch_size: 512
  memory_limiter:
    check_interval: 1s
    limit_mib: 256
  transform:
    metric_statements:
      - context: datapoint
        statements:
        - set(attributes["client"], resource.attributes["maykin.saas.client"])
        - set(attributes["target"], resource.attributes["maykin.saas.target"])

exporters:
  debug:
    verbosity: detailed
  # Exposes a metrics endpoint that prometheus can scrape
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: otel  # this becomes a prefix in the prometheus metrics: `otel_*`
    const_labels:
      environment: local_otel_collector
    resource_to_telemetry_conversion:
      enabled: true

service:
  # extensions: [basicauth/server]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, transform, batch]
      exporters: [debug, prometheus]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]
