# Generated by Django 5.2.7 on 2025-11-25 14:11

import uuid

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Verzoek",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatiecode (UUID4) voor het Verzoek.",
                        unique=True,
                    ),
                ),
                (
                    "geometrie",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        help_text="Point, LineString of Polygon object dat de locatie van het verzoek representeert.",
                        null=True,
                        srid=4326,
                        verbose_name="geometrie",
                    ),
                ),
                (
                    "aanvraag_gegevens",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="JSON data voor validatie van het VerzoekType.",
                        verbose_name="aanvraag gegevens",
                    ),
                ),
                (
                    "bijlagen",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=100, verbose_name="documents"
                        ),
                        blank=True,
                        default=list,
                        help_text="Eventuele bijlagen van het Verzoek (URNs van documenten).",
                        size=None,
                    ),
                ),
            ],
            options={
                "verbose_name": "Verzoek",
                "verbose_name_plural": "Verzoeken",
            },
        ),
        migrations.CreateModel(
            name="VerzoekType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatiecode (UUID4) voor het VerzoekType",
                        unique=True,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Naam voor het VerzoekType",
                        max_length=100,
                        verbose_name="naam",
                    ),
                ),
                (
                    "toelichting",
                    models.TextField(
                        blank=True,
                        help_text="Uitleg over het VerzoekType",
                        verbose_name="toelichting",
                    ),
                ),
                (
                    "opvolging",
                    models.CharField(
                        choices=[
                            ("niet", "Leidt niet tot een zaak"),
                            ("mogelijk", "Leidt mogelijk tot een zaak"),
                            ("altijd", "Leidt altijd tot een zaak"),
                            ("meerdere", "Leidt altijd tot meerdere zaken"),
                        ],
                        default="niet",
                        help_text="Opvolging over het VerzoekType",
                        max_length=20,
                        verbose_name="opvolging",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Datum waarop het VerzoekType is aangemaakt",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified_at",
                    models.DateField(
                        auto_now=True,
                        help_text="Laatste datum waarop het VerzoekType is gewijzigd",
                        verbose_name="modified at",
                    ),
                ),
            ],
            options={
                "verbose_name": "VerzoekType",
                "verbose_name_plural": "VerzoekTypes",
            },
        ),
        migrations.CreateModel(
            name="VerzoekBetaling",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kenmerken",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=100, verbose_name="kenmerken"
                        ),
                        blank=True,
                        default=list,
                        help_text="Eventuele kenmerken van de betaling.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "bedrag",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Het bedrag van de betaling.",
                        max_digits=10,
                        null=True,
                        verbose_name="bedrag",
                    ),
                ),
                (
                    "voltooid",
                    models.BooleanField(
                        default=False,
                        help_text="Geeft aan of de betaling voltooid is.",
                        verbose_name="voltooid",
                    ),
                ),
                (
                    "transactie_datum",
                    models.DateTimeField(
                        blank=True,
                        help_text="Datum en tijd van de transactie.",
                        null=True,
                        verbose_name="transactie datum",
                    ),
                ),
                (
                    "transactie_referentie",
                    models.CharField(
                        blank=True,
                        help_text="Referentie van de transactie.",
                        max_length=100,
                        verbose_name="transactie referentie",
                    ),
                ),
                (
                    "verzoek",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="betaling",
                        to="verzoeken.verzoek",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verzoek Betaling",
                "verbose_name_plural": "Verzoeken Betaling",
            },
        ),
        migrations.CreateModel(
            name="VerzoekBron",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        blank=True,
                        help_text="Naam van de bron.",
                        max_length=100,
                        verbose_name="bron naam",
                    ),
                ),
                (
                    "kenmerk",
                    models.CharField(
                        blank=True,
                        help_text="Kenmerk van de bron.",
                        max_length=255,
                        verbose_name="bron kenmerk",
                    ),
                ),
                (
                    "verzoek",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bron",
                        to="verzoeken.verzoek",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verzoek Bron",
                "verbose_name_plural": "Verzoeken Bron",
            },
        ),
        migrations.AddField(
            model_name="verzoek",
            name="verzoek_type",
            field=models.ForeignKey(
                help_text="Type van het Verzoek.",
                on_delete=django.db.models.deletion.PROTECT,
                to="verzoeken.verzoektype",
            ),
        ),
        migrations.CreateModel(
            name="VerzoekTypeVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveSmallIntegerField(
                        help_text="Integer-versie van het VerzoekType.",
                        verbose_name="version",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Datum waarop de versie is gemaakt",
                        verbose_name="created at",
                    ),
                ),
                (
                    "modified_at",
                    models.DateField(
                        auto_now=True,
                        help_text="Laatste datum waarop de versie is gewijzigd",
                        verbose_name="modified at",
                    ),
                ),
                (
                    "published_at",
                    models.DateField(
                        blank=True,
                        help_text="Datum waarop de versie is gepubliceerd",
                        null=True,
                        verbose_name="published_at",
                    ),
                ),
                (
                    "aanvraag_gegevens_schema",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="JSON schema voor validatie van VerzoekType",
                        verbose_name="aanvraag gegevens schema",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("draft", "Draft"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="draft",
                        help_text="Status van het VerzoekTypeVersion",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "verzoek_type",
                    models.ForeignKey(
                        help_text="Het VerzoekType waartoe deze versie behoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="verzoeken.verzoektype",
                    ),
                ),
            ],
            options={
                "ordering": ["-version", "-created_at"],
                "unique_together": {("verzoek_type", "version")},
            },
        ),
    ]
