# Generated by Django 5.2.11 on 2026-02-09 12:44

import uuid

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models

import openvtb.utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Verzoek",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatiecode (UUID4) voor het Verzoek.",
                        unique=True,
                    ),
                ),
                (
                    "version",
                    models.PositiveSmallIntegerField(
                        help_text="Versie van VerzoekType om het gegevensschema van het verzoek te valideren",
                        verbose_name="version",
                    ),
                ),
                (
                    "geometrie",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        help_text="Point, LineString of Polygon object dat de locatie van het verzoek representeert.",
                        null=True,
                        srid=4326,
                        verbose_name="geometrie",
                    ),
                ),
                (
                    "aanvraag_gegevens",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="JSON data voor validatie van het VerzoekType.",
                        verbose_name="aanvraag gegevens",
                    ),
                ),
                (
                    "is_ingediend_door",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="JSON-object dat aangeeft door wie het verzoek is ingediend. Kan één van de volgende vormen hebben:\n- authentiekeVerwijzing: object met een 'urn' string (bijv. 'urn:...')\n- nietAuthentiekePersoonsgegevens: object met persoonsgegevens zoals voornaam, achternaam, geboortedatum, emailadres, telefoonnummer, postadres en verblijfsadres\n- nietAuthentiekeOrganisatiegegevens: object met organisatiegegevens zoals statutaireNaam, bezoekadres, postadres, emailadres en telefoonnummer\nDit JSON-object wordt gebruikt voor validatie van het VerzoekType.",
                        verbose_name="Is ingediend door",
                    ),
                ),
                (
                    "is_gerelateerd_aan",
                    openvtb.utils.fields.URNField(
                        blank=True,
                        help_text="URN naar de ZAAK of het PRODUCT. Bijvoorbeeld: `urn:nld:gemeenteutrecht:zaak:zaaknummer:000350165`",
                        max_length=255,
                        verbose_name="is gerelateerd aan",
                    ),
                ),
                (
                    "kanaal",
                    models.CharField(
                        blank=True,
                        help_text="Geeft aan via welk kanaal dit verzoek is binnengekomen.",
                        max_length=200,
                        verbose_name="kanaal",
                    ),
                ),
                (
                    "authenticatie_context",
                    openvtb.utils.fields.URNField(
                        blank=True,
                        help_text="authentication context urn",
                        max_length=255,
                        verbose_name="authenticatie context",
                    ),
                ),
                (
                    "informatie_object",
                    openvtb.utils.fields.URNField(
                        blank=True,
                        help_text="URN naar het ENKELVOUDIGINFORMATIEOBJECT zijnde het verzoek als document zoals gezien door de aanvrager.",
                        max_length=255,
                        verbose_name="informatie object",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verzoek",
                "verbose_name_plural": "Verzoeken",
            },
        ),
        migrations.CreateModel(
            name="VerzoekType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatiecode (UUID4) voor het VerzoekType",
                        unique=True,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="Naam voor het VerzoekType",
                        max_length=100,
                        verbose_name="naam",
                    ),
                ),
                (
                    "toelichting",
                    models.TextField(
                        blank=True,
                        help_text="Uitleg over het VerzoekType",
                        max_length=4000,
                        verbose_name="toelichting",
                    ),
                ),
                (
                    "aangemaakt_op",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Datum waarop het VerzoekType is aangemaakt",
                        verbose_name="aangemaakt op",
                    ),
                ),
                (
                    "gewijzigd_op",
                    models.DateField(
                        auto_now=True,
                        help_text="Laatste datum waarop het VerzoekType is gewijzigd",
                        verbose_name="gewijzigd op",
                    ),
                ),
            ],
            options={
                "verbose_name": "VerzoekType",
                "verbose_name_plural": "VerzoekTypes",
            },
        ),
        migrations.CreateModel(
            name="VerzoekBetaling",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kenmerken",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            max_length=100, verbose_name="kenmerken"
                        ),
                        blank=True,
                        default=list,
                        help_text="Eventuele kenmerken van de betaling.",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "bedrag",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Het bedrag van de betaling.",
                        max_digits=10,
                        null=True,
                        verbose_name="bedrag",
                    ),
                ),
                (
                    "valuta",
                    models.CharField(
                        choices=[("EUR", "Euro")],
                        default="EUR",
                        help_text="Valuta van de betaling",
                        max_length=20,
                        verbose_name="valuta",
                    ),
                ),
                (
                    "voltooid",
                    models.BooleanField(
                        default=False,
                        help_text="Geeft aan of de betaling voltooid is.",
                        verbose_name="voltooid",
                    ),
                ),
                (
                    "transactie_datum",
                    models.DateTimeField(
                        blank=True,
                        help_text="Datum en tijd van de transactie.",
                        null=True,
                        verbose_name="transactie datum",
                    ),
                ),
                (
                    "transactie_referentie",
                    models.CharField(
                        blank=True,
                        help_text="Referentie van de transactie.",
                        max_length=100,
                        verbose_name="transactie referentie",
                    ),
                ),
                (
                    "verzoek",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="betaling",
                        to="verzoeken.verzoek",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verzoek Betaling",
                "verbose_name_plural": "Verzoeken Betaling",
            },
        ),
        migrations.CreateModel(
            name="VerzoekBron",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        blank=True,
                        help_text="Naam van de bron.",
                        max_length=100,
                        verbose_name="bron naam",
                    ),
                ),
                (
                    "kenmerk",
                    models.CharField(
                        blank=True,
                        help_text="Kenmerk van de bron.",
                        max_length=255,
                        verbose_name="bron kenmerk",
                    ),
                ),
                (
                    "verzoek",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bron",
                        to="verzoeken.verzoek",
                    ),
                ),
            ],
            options={
                "verbose_name": "Verzoek Bron",
                "verbose_name_plural": "Verzoeken Bron",
            },
        ),
        migrations.AddField(
            model_name="verzoek",
            name="verzoek_type",
            field=models.ForeignKey(
                help_text="Type van het Verzoek.",
                on_delete=django.db.models.deletion.PROTECT,
                to="verzoeken.verzoektype",
            ),
        ),
        migrations.CreateModel(
            name="VerzoekTypeVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.PositiveSmallIntegerField(
                        help_text="Integer-versie van het VerzoekType.",
                        verbose_name="version",
                    ),
                ),
                (
                    "aangemaakt_op",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Datum waarop de versie is gemaakt",
                        verbose_name="aangemaakt op",
                    ),
                ),
                (
                    "gewijzigd_op",
                    models.DateField(
                        auto_now=True,
                        help_text="Laatste datum waarop de versie is gewijzigd",
                        verbose_name="gewijzigd op",
                    ),
                ),
                (
                    "begin_geldigheid",
                    models.DateField(
                        blank=True,
                        help_text="Datum waarop de versie is gepubliceerd",
                        null=True,
                        verbose_name="begin geldigheid",
                    ),
                ),
                (
                    "einde_geldigheid",
                    models.DateField(
                        default=None,
                        help_text="Einde van de geldigheidsduur van de versie, automatisch ingesteld wanneer een nieuwere versie wordt gepubliceerd. Als de waarde wordt ingesteld voordat de versie wordt gepubliceerd, wordt deze overschreven met de publicatiedatum.",
                        null=True,
                        verbose_name="einde geldigheid",
                    ),
                ),
                (
                    "aanvraag_gegevens_schema",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="JSON schema voor validatie van VerzoekType",
                        verbose_name="aanvraag gegevens schema",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("draft", "Draft"),
                            ("deprecated", "Deprecated"),
                        ],
                        default="draft",
                        help_text="Status van het VerzoekTypeVersion",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "verzoek_type",
                    models.ForeignKey(
                        help_text="Het VerzoekType waartoe deze versie behoort.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="verzoeken.verzoektype",
                    ),
                ),
            ],
            options={
                "ordering": ["-version", "-aangemaakt_op"],
                "unique_together": {("verzoek_type", "version")},
            },
        ),
        migrations.CreateModel(
            name="Bijlage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatiecode (UUID4) voor het Bijlage.",
                        unique=True,
                    ),
                ),
                (
                    "informatie_object",
                    openvtb.utils.fields.URNField(
                        blank=True,
                        help_text="URN naar het ENKELVOUDIGINFORMATIEOBJECT. Bijvoorbeeld: `urn:nld:gemeenteutrecht:informatieobject:uuid:717815f6-1939-4fd2-93f0-83d25bad154e`",
                        max_length=255,
                        verbose_name="informatie object",
                    ),
                ),
                (
                    "toelichting",
                    models.TextField(
                        blank=True,
                        help_text="Toelichting van de bijlage, zoals die door eindgebruikers gezien kan worden in bijvoorbeeld een portaal. Typisch is dit dezelfde omschrijving als die van het INFORMATIEOBJECT.",
                        max_length=4000,
                        verbose_name="toelichting",
                    ),
                ),
                (
                    "verzoek",
                    models.ForeignKey(
                        help_text="Bijlagen gekoppeld aan het Verzoek.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bijlagen",
                        to="verzoeken.verzoek",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bijlage",
                "verbose_name_plural": "Bijlagen",
                "unique_together": {("verzoek", "informatie_object")},
            },
        ),
        migrations.CreateModel(
            name="BijlageType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke identificatiecode (UUID4) voor het BijlageType.",
                        unique=True,
                    ),
                ),
                (
                    "informatie_objecttype",
                    openvtb.utils.fields.URNField(
                        blank=True,
                        help_text="URN van het INFORMATIEOBJECTTYPE. Bijvoorbeeld: `urn:nld:gemeenteutrecht:informatieobjecttype:uuid:717815f6-1939-4fd2-93f0-83d25bad154e`",
                        max_length=255,
                        verbose_name="informatie objecttype",
                    ),
                ),
                (
                    "omschrijving",
                    models.TextField(
                        blank=True,
                        help_text="Omschrijving van het soort bijlage, zoals dat door eind gebruikers gezien kan worden in bijvoorbeeld een portaal. Typisch is dit dezelfde omschrijving als die van het INFORMATIEOBJECTTYPE.",
                        verbose_name="omschrijving",
                    ),
                ),
                (
                    "verzoek_type_version",
                    models.ForeignKey(
                        help_text="Bijlagetypen gekoppeld aan het VerzoekTypeVersion.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bijlage_typen",
                        to="verzoeken.verzoektypeversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "BijlageType",
                "verbose_name_plural": "BijlageTypen",
                "unique_together": {("verzoek_type_version", "informatie_objecttype")},
            },
        ),
    ]
