# Generated by Django 5.2.15 on 2026-06-25 09:03

from django.db import migrations

import openvtb.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("verzoeken", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="verzoek",
            name="mede_initiator",
            field=openvtb.utils.fields.URNField(
                blank=True,
                help_text="Verwijzing naar een authentieke of niet-authentieke persoon of organisatie. Dit kan een URN van een NATUURLIJK PERSOON of NIET-NATUURLIJK PERSOON zijn. Bijvoorbeeld: `urn:nld:brp:bsn:111222333`, `urn:nld:hr:kvknummer:444555666`, `urn:nld:hr:kvknummer:444555666:vestigingsnummer:777888999` of `urn:nld:klant:klantnummer:610541501`",
                max_length=255,
                verbose_name="mede initiator",
            ),
        ),
    ]
