# Generated by Django 5.2.17 on 2026-10-06 12:16

import django.core.validators
from django.db import migrations, models

import openvtb.utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("verzoeken", "0002_verzoek_mede_initiator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="verzoek",
            name="verzoek_informatie_object",
        ),
        migrations.RemoveField(
            model_name="verzoek",
            name="verzoek_taal",
        ),
        migrations.AddField(
            model_name="verzoek",
            name="informatie_object",
            field=openvtb.utils.fields.URNField(
                blank=True,
                help_text="URN naar het ENKELVOUDIGINFORMATIEOBJECT zijnde het verzoek als document zoals gezien door de aanvrager.Bijvoorbeeld: `urn:nld:gemeenteutrecht:informatieobject:uuid:717815f6-1939-4fd2-93f0-83d25bad154e`",
                max_length=255,
                verbose_name="informatie object",
            ),
        ),
        migrations.AddField(
            model_name="verzoek",
            name="taal",
            field=models.CharField(
                blank=True,
                default="nl",
                help_text="De taal, volgens het IANA Language Subtag Registry, waarin het verzoek is gedaan. In de meest praktische vorm is dit de taal van de vragen maar het is mogelijk dat de antwoorden in een andere taal zijn gedaan. Bijvoorbeeld door iemand die wel Nederlands kan lezen maar niet kan schrijven.",
                max_length=2,
                validators=[django.core.validators.MinLengthValidator(limit_value=2)],
                verbose_name="taal",
            ),
        ),
    ]
