name: Check MacOS compatibility

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
      - stable/*
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

# least privilege as default, should be overridden per job if necessary
permissions:
  contents: read

jobs:
  macos-deps:
    name: Install dev dependencies on MacOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.12'
      - name: Install OS-level packages
        run: |
          brew install pkg-config
      - name: Install dependencies
        run: |
          export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/
          pip install -r requirements/dev.txt \
            --use-pep517 \
            --use-feature=no-binary-enable-wheel-cache
        env:
          STATIC_DEPS: 'true'
