name: Check MacOS compatibility

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - main
      - stable/*
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

# least privilege as default, should be overridden per job if necessary
permissions:
  contents: read

jobs:
  macos-deps:
    name: Install dev dependencies on MacOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: '3.12'
      - name: Install OS-level packages
        run: |
          brew install pkg-config
      - name: Install dependencies
        run: |
          export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/opt/openssl/lib/
          pip install -r requirements/dev.txt \
            --use-pep517 \
            --use-feature=no-binary-enable-wheel-cache
        env:
          STATIC_DEPS: 'true'
